spring:
  profiles:
    active: dev
  application:
    name: lazybone
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 9111
  context-path: /lazybone
logging:
  level: org.hibernate.sql=debug
eureka:
  instance:
    hostname: lazybone
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://lazybone:8761/eureka/
---
spring:
  profiles: production
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.5.5.60:3306/lazybone?characterEncoding=utf8&useSSL=false
    username: lazybone
    password: ailab2020
    type: com.zaxxer.hikari.HikariDataSource
---
spring:
  profiles: dev
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Mysql
    platform: h2
server:
  port: 9113